version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_CICDGitmuz22pzxProject
  gitServerName: SIQAGitHubTest
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
